import { DefaultTheme } from 'react-native-paper';
import { light, dark } from './colors';

// MR & FT – react-native-paper MD3 themes
// Roundness 16 for premium card feel

export const lightTheme = {
  ...DefaultTheme,
  dark: false,
  roundness: 16,
  colors: {
    ...DefaultTheme.colors,
    primary:              light.primary,
    primaryContainer:     light.primaryLight,
    secondary:            light.secondary,
    secondaryContainer:   light.secondaryLight,
    tertiary:             light.accent,
    tertiaryContainer:    light.accentLight,
    surface:              light.card,
    surfaceVariant:       light.cardAlt,
    background:           light.background,
    error:                light.error,
    errorContainer:       light.errorLight,
    onPrimary:            '#FFFFFF',
    onPrimaryContainer:   light.text,
    onSecondary:          '#FFFFFF',
    onSecondaryContainer: light.text,
    onTertiary:           '#FFFFFF',
    onTertiaryContainer:  light.text,
    onSurface:            light.text,
    onSurfaceVariant:     light.textSecondary,
    onBackground:         light.text,
    onError:              '#FFFFFF',
    onErrorContainer:     light.text,
    outline:              light.border,
    outlineVariant:       light.midGrey,
    shadow:               light.shadow,
    scrim:                light.overlay,
    inverseSurface:       light.black,
    inverseOnSurface:     '#FFFFFF',
    inversePrimary:       light.accentLight,
    elevation:            DefaultTheme.colors.elevation,
  },
};

export const darkTheme = {
  ...DefaultTheme,
  dark: true,
  mode: 'adaptive',
  roundness: 16,
  colors: {
    ...DefaultTheme.colors,
    primary:              dark.primary,
    primaryContainer:     dark.primaryLight,
    secondary:            dark.secondary,
    secondaryContainer:   dark.secondaryLight,
    tertiary:             dark.accent,
    tertiaryContainer:    dark.accentLight,
    surface:              dark.card,
    surfaceVariant:       dark.cardAlt,
    background:           dark.background,
    error:                dark.error,
    errorContainer:       dark.errorLight,
    onPrimary:            dark.background,
    onPrimaryContainer:   dark.text,
    onSecondary:          dark.background,
    onSecondaryContainer: dark.text,
    onTertiary:           dark.background,
    onTertiaryContainer:  dark.text,
    onSurface:            dark.text,
    onSurfaceVariant:     dark.textSecondary,
    onBackground:         dark.text,
    onError:              dark.background,
    onErrorContainer:     dark.text,
    outline:              dark.border,
    outlineVariant:       dark.midGrey,
    shadow:               dark.shadow,
    scrim:                dark.overlay,
    inverseSurface:       dark.text,
    inverseOnSurface:     dark.background,
    inversePrimary:       dark.accentLight,
    elevation: {
      level0: 'transparent',
      level1: dark.card,
      level2: dark.card,
      level3: dark.cardAlt,
      level4: dark.cardAlt,
      level5: dark.cardAlt,
    },
  },
};

export const theme = lightTheme;
export default theme;
